Description of error
Home > @al_spk > error.m
error
PURPOSE
Report an error that occurred in a spike object
SYNOPSIS
function msgOut = error(s,msgIn,caller)
DESCRIPTION
 Report an error that occurred in a spike object
 function msgOut = error(s,msgIn)
 INPUT
 s            A @spikes object
 msgIn        Part of the message reported to the user.
 caller        Function that threw the error.
 OUTPUT
  msg        The complete message.
 BK  - 25.11.2000  - Last Change $Date: 2000/12/05 07:33:59 $
 $Revision: 1.1 $
CROSS-REFERENCE INFORMATION
This function calls:
error Report an error that occurred in a spike object
This function is called by:
al_spk Constructor for the @al_spk class
error Report an error that occurred in a spike object
spk_Align align all time data
spk_AnalogAngularDist calculates the angular distance between signal S1 to S2
spk_AnalogCheckChan check for consistency of analog channel data, returns number of channels.
spk_AnalogCircularDist calculates the circular distance between XY signal S1 and signal S2
spk_AnalogEuclidDist calculates the euclidean distance from signal SigChans to signal RefChans
spk_AnalogFindNextBin Go through analog bins until a bin is found.
spk_AnalogMean Calculate mean value of analog channel
spk_AnalogPrctile Calculate percentiles of analog channel
spk_AnalogXCorr cross correlation between two channels
spk_CheckCurrentChannels
spk_EventTimePlot plots events on an x time axis
spk_NLX_get connects to a cheetah data acquisition software and writes data into a
spk_NLX_readNCS reads spike data from a neuralynx *.nse file
spk_NLX_readNSE reads spike data from a neuralynx *.nse file
spk_SpikeDensity Calculates the Spike Density Function over trials listed in s.currenttrials
spk_SpikeRevCorr count spikes related to reverse correlation stimulus
spk_SpikeTimePrecision set the temporal precision of timestamps
spk_SpikeWinrate calculate rate of the current trials
spk_TrialEventWindow returns the time window between two specified events
spk_TrialGroups group trials according to a trialcode label
spk_TrialNum returns and check for number of trials in @al_spk object
spk_addTrialData Add trial data for svereal datatypes
spk_cat concatenation of @al_spk objects
spk_event2NLXts
spk_eventdiff calculates time differences of two types of events in the trials given in
spk_findtrials_AND find trials with trialcodes given in varargin
spk_findtrials_OR find trials with trialcodes given in varargin
spk_getEpoch ---------------------------------------
spk_histogram calculates histograms for spikedata defined by s.currenttrials and s.currentchan
spk_readcortex reads a cortex file in @al_spk object
spk_revcorrtemp calculates a reverse correlation to a temporal sequence of different stimuli
spk_set set the fields of an @al_spk object
subsasgn Subscript assignmemt for the @al_spk object.
subsref Subsref for al_spk Objects
SOURCE CODE
function msgOut = error(s,msgIn,caller)
% Report an error that occurred in a spike object
%
% function msgOut = error(s,msgIn)
% INPUT
% s            A @spikes object
% msgIn        Part of the message reported to the user.
% caller        Function that threw the error.
% OUTPUT
%  msg        The complete message.
%
% BK  - 25.11.2000  - Last Change $Date: 2000/12/05 07:33:59 $
% $Revision: 1.1 $
if nargin ==3
   msg = ['@MANE2 error in ' caller ':' msgIn];
else
   msg =['@MANE2 error: ' msgIn];
end
disp(msg);
error(' ');
if nargout ==1
   msgOut = msg;
end