Description of spk_AnalogAlign
Home > @al_spk > spk_AnalogAlign.m
spk_AnalogAlign
PURPOSE
Aligns values of analog channel to value at a given point in time.
SYNOPSIS
function s = spk_AnalogAlign(s,ChanName,AlignTime)
DESCRIPTION
 Aligns values of analog channel to value at a given point in time.
 s = spk_AnalogAlign(s,ChanName,AlignTime)
 Input:
 ChanName ...... Name of an analog channel as in s.analog
 AlignTime .......
CROSS-REFERENCE INFORMATION
This function calls:
spk_AnalogTimeVec retrieves times of analog data bins
spk_TrialNum returns and check for number of trials in @al_spk object
spk_findAnalog finds an analog channel, or channels featuring a pattern
spk_set set the fields of an @al_spk object
This function is called by:
SOURCE CODE
function s = spk_AnalogAlign(s,ChanName,AlignTime)
% Aligns values of analog channel to value at a given point in time.
% s = spk_AnalogAlign(s,ChanName,AlignTime)
% Input:
% ChanName ...... Name of an analog channel as in s.analog
% AlignTime .......
%% get the channel index
if nargin<2 || isempty(ChanName)
    if isempty(s.currentanalog);
        iChan = 1:size(s.analog,2);
    else
        iChan = s.currentanalog;
    end
else
    iChan = spk_findAnalog(s,ChanName);
end
nChan = length(iChan);
%% get trials
numTrials = spk_TrialNum(s);
if isempty(s.currenttrials)
    s.currenttrials = 1:numTrials;
end
numCurrenttrials = length(s.currenttrials);
%% loop channels
for iCh = 1:nChan
    [nTr,numSamples] = size(s.analog{iChan(iCh)});
    s = spk_set(s,'currentanalog',iChan(iCh));
    TimeData = spk_AnalogTimeVec(s);
    [dummy,iBin] = min(abs(TimeData-AlignTime));
    s.analog{iChan(iCh)}(s.currenttrials,:) = s.analog{iChan(iCh)}(s.currenttrials,:) - repmat(s.analog{iChan(iCh)}(s.currenttrials,iBin),[1,numSamples]);
end