Description of spk_findchannel
Home > @al_spk > spk_findchannel.m
spk_findchannel
PURPOSE
get the indices of channels as appearing in s.channel
SYNOPSIS
function ChanIndex = spk_findchannel(s,ChanName)
DESCRIPTION
 get the indices of channels as appearing in s.channel
 ChanIndex = spk_findchannel(s,ChanName)
 ChanName ... cell array of channel names
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
spk_nlxget_old6 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old7 connects to a cheetah data acquisition software and writes data into a
spk_nlxget connects to a cheetah data acquisition software and writes data into a
SOURCE CODE
function ChanIndex = spk_findchannel(s,ChanName)
% get the indices of channels as appearing in s.channel
% ChanIndex = spk_findchannel(s,ChanName)
%
% ChanName ... cell array of channel names
for i = 1:length(ChanName)
    CurrIndex = strmatch(ChanName{i},s.channel);
    if isempty(CurrIndex)
        ChanIndex(i) = NaN;
    else
        ChanIndex(i) = CurrIndex;
    end
end