Description of spk_SpikeDecodeChanName
Home > @al_spk > spk_SpikeDecodeChanName.m
spk_SpikeDecodeChanName
PURPOSE
decodes channel labels of the form 'Sc1.1'
SYNOPSIS
function [ElectrodeName,ClusterNr] = spk_SpikeDecodeChanName(s)
DESCRIPTION
 decodes channel labels of the form 'Sc1.1'
 [ElectrodeName,ClusterNr] = spk_SpikeDecodeChanName(s)
 ElectrodeName ... cell array of strings
 ClusterNr ....... vector of integers
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
spk_SpikePoolElChans pools all the channels recorded from a given electrode
spk_findElectrodeChan get the index of a spike channel
spk_getElectrodeChan retrieves index for channels of a given electrode
SOURCE CODE
function [ElectrodeName,ClusterNr] = spk_SpikeDecodeChanName(s)
% decodes channel labels of the form 'Sc1.1'
%
% [ElectrodeName,ClusterNr] = spk_SpikeDecodeChanName(s)
%
% ElectrodeName ... cell array of strings
% ClusterNr ....... vector of integers
ElectrodeName = {};
ClusterNr = [];
for i=1:length(s.channel)
    [ElectrodeName{i},rem] = strtok(s.channel{i},'.');
    k = strtok(rem,'.');
    if ~isempty(k)
        ClusterNr(i) = sscanf(k,'%d');
    else
        ClusterNr(i) = NaN;
    end
end