Description of spk_findtrialcodelabel
Home > @al_spk > spk_findtrialcodelabel.m
spk_findtrialcodelabel
PURPOSE
returns the index of a trialcodelabel
SYNOPSIS
function i = spk_findtrialcodelabel(s,trialcodelabel)
DESCRIPTION
 returns the index of a trialcodelabel
 i = spk_findtrialcodelabel(s,trialcodelabel)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
spk_NLX_get connects to a cheetah data acquisition software and writes data into a
spk_findtrials_AND find trials with trialcodes given in varargin
spk_findtrials_OR find trials with trialcodes given in varargin
SOURCE CODE
function i = spk_findtrialcodelabel(s,trialcodelabel)
% returns the index of a trialcodelabel
%
% i = spk_findtrialcodelabel(s,trialcodelabel)
i = strmatch(upper(trialcodelabel),upper(s.trialcodelabel),'exact');