Description of spk_set
Home > @al_spk > spk_set.m
spk_set
PURPOSE
set the fields of an @al_spk object
SYNOPSIS
function s = spk_set(s,varargin)
DESCRIPTION
 set the fields of an @al_spk object
 function s = spk_set(s,varargin)
CROSS-REFERENCE INFORMATION
This function calls:
error Report an error that occurred in a spike object
This function is called by:
spk_AnalogAlign Aligns values of analog channel to value at a given point in time.
spk_AnalogCircularMean Calculate mean value of analog channel with circular data
spk_AnalogLine Plots line objects of current analog trials into current axes.
spk_AnalogLineXY Plots two analog channels (X vs Y) of current trials into current axes.
spk_AnalogMean Calculate mean value of analog channel
spk_AnalogPrctile Calculate percentiles of analog channel
spk_LFP_preprocess
spk_NLX_get connects to a cheetah data acquisition software and writes data into a
spk_SpikeLatency Calculates latencies of spiketrains
spk_analogSTA Spike Triggered Average of an analog channel
SOURCE CODE
function s = spk_set(s,varargin)
% set the fields of an @al_spk object
% function s = spk_set(s,varargin)
if rem(length(varargin),2)~= 0
     error('Arguments must be Property/Value pairs !');
end
numProp = length(varargin)./2;
for i = 1:numProp
     cprop = lower(varargin{i*2-1});
     cval = varargin{i*2};
     switch cprop
          case 'currenttrials'
               if size(cval,1)>1
                    cval = cval';
               end
     end
     eval(['s.' cprop ' =  cval;']);
end