Description of spk_CheckCurrentChannels
Home > @al_spk > spk_CheckCurrentChannels.m
spk_CheckCurrentChannels
PURPOSE
SYNOPSIS
function out = spk_CheckCurrentChannels(s,SetAllIfEmpty)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
error Report an error that occurred in a spike object
This function is called by:
spk_SpikeAutoCorrelation calculates the auto correlation histogram
spk_SpikeAutoCorrelation2 calculates the auto correlation histogram
spk_SpikeDensity Calculates the Spike Density Function over trials listed in s.currenttrials
spk_SpikeLatency Calculates latencies of spiketrains
spk_SpikeWinrate calculate rate of the current trials
spk_ifr calculates instantaneaous spike rate for the current trials
spk_instant calculates instantaneaous spike rate for the current trials
SOURCE CODE
function out = spk_CheckCurrentChannels(s,SetAllIfEmpty)
if isempty(s.currentchan) & SetAllIfEmpty~=0
    warning('''currentchan'' field is not set. Process all channels!');
    s.currentchan = [1:size(s.spk,1)];
elseif isempty(s.currentchan) & SetAllIfEmpty==0
    error('''currentchan'' field is not set!');
end
out =  s.currentchan;