Description of spk_gettrialcodes
Home > @al_spk > spk_gettrialcodes.m
spk_gettrialcodes
PURPOSE
returns the trial codes trials trials given in s.currenttrials ; set by >>spk_set(s,'currentrials',[ ... ])
SYNOPSIS
function [TrialCodes,TrialCodeLabelIndex] = spk_gettrialcodes(s,TrialCodeLabel)
DESCRIPTION
 returns the trial codes trials trials given in s.currenttrials ; set by >>spk_set(s,'currentrials',[ ... ])
 [TrialCodes,TrialCodeLabelIndex] = spk_gettrialcodes(s,TrialCodeLabel)
CROSS-REFERENCE INFORMATION
This function calls:
spk_findtrialcodelabel returns the index of a trialcodelabel
This function is called by:
spk_nlxget_old1 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old2 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old3 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old4 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old5 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old6 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old7 connects to a cheetah data acquisition software and writes data into a
spk_nlxget connects to a cheetah data acquisition software and writes data into a
spk_nlxreadspikedata reads spike data from a neuralynx *.nse file
SOURCE CODE
function [TrialCodes,TrialCodeLabelIndex] = spk_gettrialcodes(s,TrialCodeLabel)
% returns the trial codes trials trials given in s.currenttrials ; set by >>spk_set(s,'currentrials',[ ... ])
% [TrialCodes,TrialCodeLabelIndex] = spk_gettrialcodes(s,TrialCodeLabel)
TrialCodeLabelIndex = spk_findtrialcodelabel(s,TrialCodeLabel);
if size(s.trialcode,1)<TrialCodeLabelIndex
    TrialCodes = [];
elseif isempty(s.currenttrials)
    TrialCodes = s.trialcode(TrialCodeLabelIndex,:);
else
    TrialCodes = s.trialcode(TrialCodeLabelIndex,s.currenttrials);
end