Description of spk_AnalogChanSum
Home > @al_spk > spk_AnalogChanSum.m
spk_AnalogChanSum
PURPOSE
Sum or multiply two analog channels. First one is reference SF
SYNOPSIS
function s = spk_AnalogChanSum(s,Mode,S1Chan,S2Chan,NewChan,InverseFlag)
DESCRIPTION
 Sum or multiply two analog channels. First one is reference SF
 spk_AnalogChanSum(s,Mode,S1Chan,S2Chan,NewChan,InverseFlag)
 Mode ..... 'SUM','SUB','PROD','RATIO
 S1,S2 .... cell array of strings with X and Y channel names
 NewChan .... new name of channel
 InverseFlag ... reverses S1 and S2 in case of 'SUB' 'RATIO'
CROSS-REFERENCE INFORMATION
This function calls:
spk_AnalogCopyChan makes a copy of an analog channel within the same object
spk_AnalogTimeVec retrieves times of analog data bins
spk_findAnalog finds an analog channel, or channels featuring a pattern
This function is called by:
SOURCE CODE
function s = spk_AnalogChanSum(s,Mode,S1Chan,S2Chan,NewChan,InverseFlag)
% Sum or multiply two analog channels. First one is reference SF
% spk_AnalogChanSum(s,Mode,S1Chan,S2Chan,NewChan,InverseFlag)
% Mode ..... 'SUM','SUB','PROD','RATIO
% S1,S2 .... cell array of strings with X and Y channel names
% NewChan .... new name of channel
% InverseFlag ... reverses S1 and S2 in case of 'SUB' 'RATIO'
%% check input
if nargin<5
    InverseFlag = false;
end
%% get the channel index
iS1 = spk_findAnalog(s,S1Chan);
iS2 = spk_findAnalog(s,S2Chan);
%% copy channel data
[s,iChan] = spk_AnalogCopyChan(s,S1Chan,NewChan);
%% get time vector
tS1 = spk_AnalogTimeVec(s,S1Chan);
tS2 = spk_AnalogTimeVec(s,S1Chan);
nBin = length(tS1);
%% match time bins of signals
i = ones(1,nBin);
for iBin = 1:nBin
    [dummy,i(iBin)] = min(abs(tS1(iBin)-tS2));
end
%% calc
switch Mode
    case 'SUM'
        s.analog{iChan} = s.analog{iS1} + s.analog{iS2}(:,i);
    case 'SUB'
        if InverseFlag
            s.analog{iChan} = s.analog{iS2}(:,i) - s.analog{iS1};
        else
            s.analog{iChan} = s.analog{iS1} - s.analog{iS2}(:,i);
        end
    case 'PROD'
        s.analog{iChan} = s.analog{iS1} .* s.analog{iS2}(:,i);
    case 'RATIO'
        if InverseFlag
            s.analog{iChan} = s.analog{iS2}(:,i) ./ s.analog{iS1};
        else
            s.analog{iChan} = s.analog{iS1} ./ s.analog{iS2}(:,i);
        end
end