Description of spk_findAnalog
Home > @al_spk > spk_findAnalog.m
spk_findAnalog
PURPOSE
finds an analog channel, or channels featuring a pattern
SYNOPSIS
function [i,sf] = spk_findAnalog(s,ChanName,PatternFlag)
DESCRIPTION
 finds an analog channel, or channels featuring a pattern
 i = spk_findAnalog(s,ChanName,PatternFlag)
 i ... logical array for PatternFlag==true
       indices of length ChanName for PatternFlag==false
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
spk_AnalogAlign Aligns values of analog channel to value at a given point in time.
spk_AnalogAngularDist calculates the angular distance between signal S1 to S2
spk_AnalogCart2Pol Applies cart2pol.m to analog data.
spk_AnalogChanSum Sum or multiply two analog channels. First one is reference SF
spk_AnalogCircularDist calculates the circular distance between XY signal S1 and signal S2
spk_AnalogCopyChan makes a copy of an analog channel within the same object
spk_AnalogEuclidDist calculates the euclidean distance from signal SigChans to signal RefChans
spk_AnalogFiltFiltButter Applies a butterworth filter via filtfilt function.
spk_AnalogFindZeros finds zero bins
spk_AnalogGradient Differentiates analog channel using gradient.m. Only works on all trials.
spk_AnalogRemoveLineAlex Removes line noise via method suggested by Alex.
spk_AnalogTimeVec retrieves times of analog data bins
spk_AnalogXCorr cross correlation between two channels
spk_findAnalogBins returns analog time bins for given windows
spk_findAnalogEventBin returns analog data for a given event
spk_getAnalog extracts analog data from the object.
SOURCE CODE
function [i,sf] = spk_findAnalog(s,ChanName,PatternFlag)
% finds an analog channel, or channels featuring a pattern
% i = spk_findAnalog(s,ChanName,PatternFlag)
% i ... logical array for PatternFlag==true
%       indices of length ChanName for PatternFlag==false
if nargin<3
    PatternFlag = false;
end
if PatternFlag
    nCh = length(s.analogname);
    i = false(1,nCh);
    for iCh = 1:nCh
        k = strfind(s.analogname{iCh},ChanName);
        if ~isempty(k)
            i(iCh) = true;
        end
    end
else
    if ischar(ChanName)
        ChanName = {ChanName};
    end
    i = [];
    for iCh = 1:length(ChanName)
        CurrIndex = strmatch(ChanName{iCh},s.analogname,'exact');
        if isempty(CurrIndex)
            i(iCh) = NaN;
        else
            i(iCh) = CurrIndex;
        end
    end
end
sf = ones(1,length(i)).*NaN;
sf(~isnan(i)) = s.analogfreq(i(~isnan(i)));