Description of spk_analogtimematrix
Home > @al_spk > spk_analogtimematrix.m
spk_analogtimematrix
PURPOSE
SYNOPSIS
function t = spk_analogtimematrix(s)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
spk_analogLine
spk_analogPowerSpectrum
spk_analogSTA Spike Triggered Average of an analog channel
SOURCE CODE
function t = spk_analogtimematrix(s)
numAna = length(s.currentanalog);
for iA = s.currentanalog
    iANr = find(s.currentanalog==iA);
    [NumTrials,NumSamples] = size(s.analog{iA});
    t{iANr} = zeros(1,NumSamples);
    t{iANr}(s.analogalignbin:-1:1) = [0 : ((-1)*(s.analogfreq(iA)/1000)) : ((s.analogalignbin-1)*(-1)*(s.analogfreq(iA)/1000))];
    t{iANr}(s.analogalignbin:1:NumSamples) = [0 : (s.analogfreq(iA)/1000) : ((NumSamples-s.analogalignbin)*(s.analogfreq(iA)/1000))];
end
if numAna==1
    t = t{1};
end