Description of spk_AnalogTimeVec
Home > @al_spk > spk_AnalogTimeVec.m
spk_AnalogTimeVec
PURPOSE
retrieves times of analog data bins
SYNOPSIS
function t = spk_AnalogTimeVec(s,Chan)
DESCRIPTION
 retrieves times of analog data bins
 t = spk_AnalogTimeVec(s,Chan)
 Chan ... channel name or channel nr.
CROSS-REFERENCE INFORMATION
This function calls:
spk_findAnalog finds an analog channel, or channels featuring a pattern
This function is called by:
spk_AnalogAlign Aligns values of analog channel to value at a given point in time.
spk_AnalogAngularDist calculates the angular distance between signal S1 to S2
spk_AnalogChanSum Sum or multiply two analog channels. First one is reference SF
spk_AnalogCircularDist calculates the circular distance between XY signal S1 and signal S2
spk_AnalogCircularMean Calculate mean value of analog channel with circular data
spk_AnalogEuclidDist calculates the euclidean distance from signal SigChans to signal RefChans
spk_AnalogEventWindow returns start and end bins of a window defined by an event(s)
spk_AnalogFindNextBin Go through analog bins until a bin is found.
spk_AnalogFindPeaks finds extrem values as well as plateaus
spk_AnalogFindZeros finds zero bins
spk_AnalogIsSaturated detects trials exceeding a range of analog values
spk_AnalogLine Plots line objects of current analog trials into current axes.
spk_AnalogLine2 plots the current trials of the current ananlog channel
spk_AnalogLineXY Plots two analog channels (X vs Y) of current trials into current axes.
spk_AnalogMean Calculate mean value of analog channel
spk_AnalogPrctile Calculate percentiles of analog channel
spk_AnalogXCorr cross correlation between two channels
spk_analogPowerSpectrum
spk_findAnalogBins returns analog time bins for given windows
spk_findAnalogEventBin returns analog data for a given event
spk_getAnalog extracts analog data from the object.
SOURCE CODE
function t = spk_AnalogTimeVec(s,Chan)
% retrieves times of analog data bins
% t = spk_AnalogTimeVec(s,Chan)
%
% Chan ... channel name or channel nr.
%% get the channel index
if nargin<2 || isempty(Chan)
    if isempty(s.currentanalog);
        s.currentanalog = 1:size(s.analog,2);
    end
elseif ischar(Chan)
    s.currentanalog = spk_findAnalog(s,Chan);
elseif isnumeric(Chan)
    s.currentanalog = Chan;
end
nCh = length(s.currentanalog);
%% loop channels
for iCh = 1:nCh
    ChNr = s.currentanalog(iCh);
    SF = s.analogfreq(ChNr);% sample frequency
    aB = s.analogalignbin(ChNr);% align bin
    nB = size(s.analog{ChNr},2);% number of sample bins
    t{iCh} = zeros(1,nB);% time vector
    t{iCh}(aB:-1:1) = [0 : ((-1)*(1000/SF)) : ((aB-1)*(-1)*(1000/SF))];
    t{iCh}(aB:1:nB) = [0 : (1000/SF) : ((nB-aB)*(1000/SF))];
end
%% modify output
if nCh==1
    t = t{1};
end