Description of spk_CheckCurrentTrials
Home > @al_spk > spk_CheckCurrentTrials.m
spk_CheckCurrentTrials
PURPOSE
SYNOPSIS
function [out,s] = spk_CheckCurrentTrials(s,SetAllIfEmpty)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
spk_TrialNum returns and check for number of trials in @al_spk object
This function is called by:
spk_EventTimePlot plots events on an x time axis
spk_SpikeAutoCorrelation calculates the auto correlation histogram
spk_SpikeAutoCorrelation2 calculates the auto correlation histogram
spk_SpikeDensity Calculates the Spike Density Function over trials listed in s.currenttrials
spk_SpikeLatency Calculates latencies of spiketrains
spk_SpikeWinrate calculate rate of the current trials
spk_analogSpecGram
spk_ifr calculates instantaneaous spike rate for the current trials
spk_instant calculates instantaneaous spike rate for the current trials
SOURCE CODE
function [out,s] = spk_CheckCurrentTrials(s,SetAllIfEmpty)
if isempty(s.currenttrials) & SetAllIfEmpty~=0
%     warning('''currentrials'' field is not set. Process all Trials!');
    NumTrials = spk_TrialNum(s);
    s.currenttrials = [1:NumTrials];
elseif isempty(s.currenttrials) & SetAllIfEmpty==0
%     warning('''currentrials'' field is not set!');
end
out = s.currenttrials;