Description of spk_numtrials
Home > @al_spk > spk_numtrials.m
spk_numtrials
PURPOSE
returns and check for number of trials in @al_spk object
SYNOPSIS
function total = spk_numtrials(s)
DESCRIPTION
 returns and check for number of trials in @al_spk object
 function total = spk_numtrials(s)
 total ... total number of trials
CROSS-REFERENCE INFORMATION
This function calls:
error Report an error that occurred in a spike object
This function is called by:
spk_appendtrial append trial data to object
spk_nlxget_old1 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old2 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old3 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old4 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old5 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old6 connects to a cheetah data acquisition software and writes data into a
spk_nlxget_old7 connects to a cheetah data acquisition software and writes data into a
spk_NLX_readNCS reads spike data from a neuralynx *.nse file
spk_NLX_readNSE reads spike data from a neuralynx *.nse file
spk_TrialEventLimit returns the time window between earliest and latest event of
spk_TrialEventWindow returns the time window between two specified events
spk_addTrialData check input
spk_analogLine
spk_getevents returns the events as a cell array
spk_gettrialdata gets data of trials specified by s.currenttrials
spk_nlxget connects to a cheetah data acquisition software and writes data into a
spk_rastertrial plots a raster plot for trials given s.currenttrials
SOURCE CODE
function total = spk_numtrials(s)
% returns and check for number of trials in @al_spk object
% function total = spk_numtrials(s)
%
% total ... total number of trials
% check trial numbers
nTrials = zeros(1,6);
nTrials(1) = size(s.spk,2);
nTrials(2) = size(s.events,2);
nTrials(3) = size(s.align,2);
nTrials(4) = size(s.trialcode,2);
nTrials(5) = size(s.stimulus,2);
% nAnalogTrials = cellfun('size',s.analog,1);
if any(nTrials==0 | isnan(nTrials))
    nTrials = nTrials(nTrials~=0 & ~isnan(nTrials));
%     warning('spk_numtrials: empty fields in object !');
end
if isempty(nTrials)
    nTrials = 0;
end
total = unique(nTrials);
if length(total)>1
    error('inconsistency in number of trials !!!');
end
% function nTrials = check_array(x,dim)
% if isempty(x)
%     nTrials = NaN;
% elseif iscell(x)
%     nTrials = cellfun('size',x,dim);
% elseif isnumeric(x)
%     nTrials = size(x,dim);
% end