Description of spk_AnalogCopyChan
Home > @al_spk > spk_AnalogCopyChan.m
spk_AnalogCopyChan
PURPOSE
makes a copy of an analog channel within the same object
SYNOPSIS
function [s,iNewChan] = spk_AnalogCopyChan(s,ChanName,NewChanName)
DESCRIPTION
 makes a copy of an analog channel within the same object
CROSS-REFERENCE INFORMATION
This function calls:
spk_AnalogCheckChan check for consistency of analog channel data, returns number of channels.
spk_findAnalog finds an analog channel, or channels featuring a pattern
This function is called by:
spk_AnalogAngularDist calculates the angular distance between signal S1 to S2
spk_AnalogCart2Pol Applies cart2pol.m to analog data.
spk_AnalogChanSum Sum or multiply two analog channels. First one is reference SF
spk_AnalogCircularDist calculates the circular distance between XY signal S1 and signal S2
spk_AnalogDiff Differentiates analog channel using diff.m. Only works on all trials.
spk_AnalogEuclidDist calculates the euclidean distance from signal SigChans to signal RefChans
spk_AnalogGradient Differentiates analog channel using gradient.m. Only works on all trials.
spk_AnalogPol2Cart Applies cart2pol.m to analog data.
spk_AnalogRectify rectifies (applies abs.m) analog channel.
SOURCE CODE
function [s,iNewChan] = spk_AnalogCopyChan(s,ChanName,NewChanName)
% makes a copy of an analog channel within the same object
iChan = spk_findAnalog(s,ChanName);
n = spk_AnalogCheckChan(s);
iNewChan = n+1;
s.analogname{iNewChan} = NewChanName;
s.analog{iNewChan} = s.analog{iChan};
s.analogunits{iNewChan} = s.analogunits{iChan};
if ~isempty(s.analogtime)
    s.analogtime{iNewChan} = s.analogtime{iChan};
end
s.analogfreq(iNewChan) = s.analogfreq(iChan);
s.analogalignbin(iNewChan) = s.analogalignbin(iChan);