Description of spk_TrialNum
Home > @al_spk > spk_TrialNum.m
spk_TrialNum
PURPOSE
returns and check for number of trials in @al_spk object
SYNOPSIS
function total = spk_TrialNum(s)
DESCRIPTION
 returns and check for number of trials in @al_spk object
 function total = spk_numtrials(s)
 total ... total number of trials
CROSS-REFERENCE INFORMATION
This function calls:
error Report an error that occurred in a spike object
This function is called by:
spk_Align align all time data
spk_AnalogAlign Aligns values of analog channel to value at a given point in time.
spk_AnalogCircularMean Calculate mean value of analog channel with circular data
spk_AnalogEventWindow returns start and end bins of a window defined by an event(s)
spk_AnalogFiltFiltButter Applies a butterworth filter via filtfilt function.
spk_AnalogFindPeaks finds extrem values as well as plateaus
spk_AnalogFindZeros finds zero bins
spk_AnalogLine Plots line objects of current analog trials into current axes.
spk_AnalogLineXY Plots two analog channels (X vs Y) of current trials into current axes.
spk_AnalogMean Calculate mean value of analog channel
spk_AnalogPrctile Calculate percentiles of analog channel
spk_AnalogRemoveLine fits a sine wave of frequency f to each trial and substract the mean
spk_AnalogRemoveLineAlex Removes line noise via method suggested by Alex.
spk_AnalogRemoveLineWin fits a sine wave of frequency f to each trial and substract the mean
spk_AnalogRemoveSine fits a sine wave of frequency f to each trial and subtract the mean
spk_AnalogXCorr cross correlation between two channels
spk_CheckCurrentTrials
spk_SpikeRevCorr count spikes related to reverse correlation stimulus
spk_TrialEventLimit returns the time window between earliest and latest event of
spk_TrialEventWindow returns the time window between two specified events
spk_getAnalog extracts analog data from the object.
spk_getEventWindow returns start and end time of a window defined by an event(s)
spk_getSpikes get the spikes within a time window
SOURCE CODE
function total = spk_TrialNum(s)
% returns and check for number of trials in @al_spk object
% function total = spk_numtrials(s)
%
% total ... total number of trials
% check trial numbers
nTrials = zeros(1,6);
nTrials(1) = size(s.spk,2);
nTrials(2) = size(s.events,2);
nTrials(3) = size(s.align,2);
nTrials(4) = size(s.trialcode,2);
nTrials(5) = size(s.stimulus,2);
% nAnalogTrials = cellfun('size',s.analog,1);
if any(nTrials==0 | isnan(nTrials))
    nTrials = nTrials(nTrials~=0 & ~isnan(nTrials));
%     warning('spk_numtrials: empty fields in object !');
end
if isempty(nTrials)
    nTrials = 0;
end
total = unique(nTrials);
if length(total)>1
    error('inconsistency in number of trials !!!');
end
% function nTrials = check_array(x,dim)
% if isempty(x)
%     nTrials = NaN;
% elseif iscell(x)
%     nTrials = cellfun('size',x,dim);
% elseif isnumeric(x)
%     nTrials = size(x,dim);
% end