Description of spk_nlxget_old1
Home > @al_spk > construction > spk_nlxget_old1.m
spk_nlxget_old1
PURPOSE
connects to a cheetah data acquisition software and writes data into a
SYNOPSIS
function s = spk_nlxget(s,p,dofun)
DESCRIPTION
 connects to a cheetah data acquisition software and writes data into a
 @al_spk object
 object is continously assigned the base workspace as variable SPK or is
 written into the figures ('tag','nlx_control') userdata.
 s ....... @al_spk object
 p ....... cheetah acquisition settings (struct)
 dofun ... cell array with functions to evaluate after every trial
           first cell of a row is the function, every other cell of the
           are the input arguments of the function
CROSS-REFERENCE INFORMATION
This function calls:
error Report an error that occurred in a spike object
spk_findtrialcodelabel returns the index of a trialcodelabel
spk_gettrialcodes returns the trial codes trials trials given in s.currenttrials ; set by >>spk_set(s,'currentrials',[ ... ])
spk_numtrials returns and check for number of trials in @al_spk object
This function is called by:
SUBFUNCTIONS
function [evTime,evID,evTTL,evBINhi,evBINlo,evcnt] = registerevent(eventdata,evTime,evID,evTTL,evBINhi,evBINlo,evcnt)
function printeventmessage(logfid,evTime,evID,evTTL,evBINhi,evBINlo,p,evcnt)
function [spikedata,flushnum] = flushspikes(cheetah,cheetahobjname,flushwin)
function [eventdata,flushnum] = flushevents(cheetah,cheetahobjname,flushwin)
SOURCE CODE
function s = spk_nlxget(s,p,dofun)
% connects to a cheetah data acquisition software and writes data into a
% @al_spk object
% object is continously assigned the base workspace as variable SPK or is
% written into the figures ('tag','nlx_control') userdata.
%
% s ....... @al_spk object
% p ....... cheetah acquisition settings (struct)
% dofun ... cell array with functions to evaluate after every trial
%           first cell of a row is the function, every other cell of the
%           are the input arguments of the function
global DO_GET_NLX_DATA
%++++++++++++++++++++++ connect to cheetah +++++++++++++++++++++++++++++++++
cheetah = actxserver('Cheetah.ExperimentControl');
h = msgbox('Make sure to RECORD the CHEETAH DATA by starting the CheetahEventResponder executable or by pushing the RED record button manually !!!','NEURALYNX control','warn');
uiwait;
%++++++++++++++++++++++ prepare logfile+++++++++++++++++++++++++++++++++++++
currtime = now;
currdate = datestr(now,30);
logfile = ['log\NLX_' currdate(1:8) '.txt'];
if exist(logfile,'file');
    fpermission = 'a';
else
    fpermission = 'w';
end
logfid = fopen(logfile,fpermission);
fprintf(1,['\n']);
fprintf(1,['-------------------------------------------------------------------------------\n']);
fprintf(1,(strrep(['write to ' fullfile(cd,logfile) ' !'],'\','/')));
fprintf(1,['\n']);
fprintf(1,['-------------------------------------------------------------------------------\n']);
fprintf(logfid,['\n']);
fprintf(logfid,['-------------------------------------------------------------------------------\n']);
fprintf(logfid,['log file opened: ' datestr(currtime,0) ' NLX time: %u\n'],invoke(cheetah,'GetTimeStampAsDouble'));
fprintf(logfid,['-------------------------------------------------------------------------------\n']);
%++++++++++++++++++++++ flush spike buffer from useless spike data
flushwin = [0 invoke(cheetah,'GetTimeStampAsDouble')];
[spikedata,flushnum] = flushspikes(cheetah,p.SpikeObjName{1},flushwin);
fprintf(1,['\nSPIKES: %5u flushed \t%u %u'],flushnum,flushwin(1),flushwin(2));
fprintf(logfid,['\nSPIKES: %5u flushed \t%u %u'],flushnum,flushwin(1),flushwin(2));
[eventdata,flushnum] = flushevents(cheetah,p.EventObjName,flushwin);
fprintf(1,['\nEVENTS: %5u flushed \t%u %u\n'],flushnum,flushwin(1),flushwin(2));
fprintf(logfid,['\nEVENTS: %5u flushed \t%u %u\n'],flushnum,flushwin(1),flushwin(2));
%++++++++++++++++++++++ check object +++++++++++++++++++++++++++++++++
spk_BlockInd = spk_findtrialcodelabel(s,'block');
if isempty(spk_BlockInd)
    s.trialcodelabel = cat(2,s.trialcodelabel,{'block'});
    spk_BlockInd = length(s.trialcodelabel);
end
%--------------------------------------------------------------------
spk_CndInd = spk_findtrialcodelabel(s,'condition');
if isempty(spk_CndInd)
    s.trialcodelabel = cat(2,s.trialcodelabel,{'condition'});
    spk_CndInd = length(s.trialcodelabel);
end
%--------------------------------------------------------------------
spk_PresentNrInd = spk_findtrialcodelabel(s,'presentationnr');
if isempty(spk_PresentNrInd)
    s.trialcodelabel = cat(2,s.trialcodelabel,{'presentationnr'});
    spk_PresentNrInd = length(s.trialcodelabel);
end
%--------------------------------------------------------------------
spk_trialcountInd = spk_findtrialcodelabel(s,'trialcount');
if isempty(spk_trialcountInd)
    s.trialcodelabel = cat(2,s.trialcodelabel,{'trialcount'});
    spk_trialcountInd = length(s.trialcodelabel);
end
%--------------------------------------------------------------------
spk_timeInd = spk_findtrialcodelabel(s,'time');
if isempty(spk_timeInd)
    s.trialcodelabel = cat(2,s.trialcodelabel,{'time'});
    spk_timeInd = length(s.trialcodelabel);
end
%--------------------------------------------------------------------
spk_TrialInd = spk_findtrialcodelabel(s,'trialnr');
if isempty(spk_TrialInd)
    s.trialcodelabel = cat(2,s.trialcodelabel,{'trialnr'});
    spk_TrialInd = length(s.trialcodelabel);
end
trialcnt2 = spk_gettrialcodes(s,'trialnr',[]);
if isempty(trialcnt2)
    trialcnt2 = 0;
else
    trialcnt2 = max(spk_gettrialcodes(s,'trialnr',[]));
end
%--------------------------------------------------------------------
if isempty(s.channel)
    spk_ChanInd = [1:p.SpikeChanNum];
    s.channel = cellstr(num2str([1:p.SpikeChanNum]'));
end
%--------------------------------------------------------------------
if isempty(s.eventlabel)
    s.eventlabel = p.EventName;
end
%--------------------------------------------------------------------
if isempty(s.date)
    s.date = datestr(now,30);
end
%--------------------------------------------------------------------
% timestmaps in milliseconds
s.timeorder = -3;
%+++++++++++++++++++++ initialise ++++++++++++++++++++++++++++++++
spkTime     = zeros(1,3000);
spkChannel  = zeros(1,3000);
spkCell     = zeros(1,3000);
evcnt = 0;
evTime      = zeros(1,200);
evID        = zeros(1,200);
evTTL       = zeros(1,200);
evBINhi       = char(200,8);
evBINlo       = char(200,8);
cndTime      = zeros(1,200);
cndID        = zeros(1,200);
cndTTL       = zeros(1,200);
cndBINhi       = char(200,8);
cndBINlo       = char(200,8);
paramcnt=0;
paramTime      = zeros(1,200);
paramID        = zeros(1,200);
paramTTL       = zeros(1,200);
paramBINhi       = char(200,8);
paramBINlo       = char(200,8);
currBlock = NaN;
currCnd = NaN;
trialcnt = spk_numtrials(s);% trial counter of READ trials for the current loop
% dont uncomment !! trialcnt2 is trial counter for data object
trialcnt3 = 0;% counts trial starts in this session
trialcnt4 = zeros(1,p.PresentationNum).*NaN;% current presented array of READ trials in Object
TRIAL_HANDBRAKE = 1;
spkcnt = 0;
paramcnt = 0;
do_READ_flag = 1;
is_READ_flag = 0;
FH = findobj('type','figure','tag','nlx_control');
%++++++++++++++ prepare plots and analyses ++++++++++++++++++++++++++++++++++++
for f = 1:size(dofun,1)
    feval(dofun{f,:},s,[],p);
end
%+++++++++++++++++++++ collect data ++++++++++++++++++++++++++++++++
while DO_GET_NLX_DATA
    %______________________________________________________________________
    % wait for event
    while (eventdata(1) < 0) | (eventdata(3) == 0)
        pause(.01);
        eventdata = invoke(cheetah,'GetEventDataAsDouble',p.EventObjName);
        if ~DO_GET_NLX_DATA;break;end
    end
    if ~DO_GET_NLX_DATA;break;end
    %--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    % trial start event, reset variables
    if eventdata(3)==p.TrialStartEvent
        TRIAL_HANDBRAKE = 0;
        % reset runnning variables
        trialcnt3 = trialcnt3 + 1;
        trialcnt4 = zeros(1,p.PresentationNum).*NaN;
        currTrialTime = now;
        do_READ_flag = 1;
        is_READ_flag = 0;
        currCnd = NaN;
        currBlock = NaN;
        evcnt = 0;
        evTime(:) = 0;evID(:) = 0;evTTL(:) = 0;evBINhi(:) = '0';evBINlo(:) = '0';
        cndcnt = 0;
        cndTime(:) = 0;cndID(:) = 0;cndTTL(:) = 0;cndBINhi(:) = '0';cndBINlo(:) = '0';
        paramcnt = 0;
        paramTime(:) = 0;paramID(:) = 0;paramTTL(:) = 0;paramBINhi(:) = '0';paramBINlo(:) = '0';
        paramArray = [];
        spkTime(:)      = 0;
        spkChannel(:)   = 0;
        spkCell(:)      = 0;
        fprintf(1,'\n\nNEW TRIAL %u %u %u (trial read, trials started, trials in SPK)',trialcnt,trialcnt3,trialcnt2);
        fprintf(logfid,'\n\nNEW TRIAL %u %u %u (trial read, trials started, trials in SPK)',trialcnt,trialcnt3,trialcnt2);
        % empty spike buffer from useless spike data
        flushwin = [0 eventdata(1)];
        if spikedata(1)<flushwin(2)
            [spikedata,flushnum] = flushspikes(cheetah,p.SpikeObjName{1},flushwin);
            fprintf(logfid,['\nSPIKES: %5u flushed \t%u %u'],flushnum,flushwin(1),flushwin(2));
        end
    end
    %--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    % register event
    [evTime,evID,evTTL,evBINhi,evBINlo,evcnt] = registerevent(eventdata,evTime,evID,evTTL,evBINhi,evBINlo,evcnt);
    printeventmessage(logfid,evTime,evID,evTTL,evBINhi,evBINlo,p,evcnt);
    %--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    %______________________________________________________________________
    % reaction
    if  eventdata(3)==p.SendConditionStart%-------------------------------------------------------------------------------------------------
        paramcnt = 0;
        eventdata(1:3) = -1001;
        % read upcoming events as parameter values
        while (eventdata(1) < 0) | (eventdata(3) ~= p.SendConditionEnd)
            eventdata = invoke(cheetah,'GetEventDataAsDouble',p.EventObjName);
            if (eventdata(1) < 0);
                pause(.01);
            elseif (eventdata(1) > 0 & eventdata(3) > 0);
                if (eventdata(3)~= p.SendConditionEnd)
                    [cndTime,cndID,cndTTL,cndBINhi,cndBINlo,cndcnt] = registerevent(eventdata,cndTime,cndID,cndTTL,cndBINhi,cndBINlo,cndcnt);
                    currCnd(cndcnt) = cndTTL(cndcnt);
                elseif (eventdata(3)== p.SendConditionEnd)
                    [evTime,evID,evTTL,evBINhi,evBINlo,evcnt] = registerevent(eventdata,evTime,evID,evTTL,evBINhi,evBINlo,evcnt);
                    printeventmessage(logfid,evTime,evID,evTTL,evBINhi,evBINlo,p,evcnt);
                    break;
                end
            end
        end
        % conditions from cortex format [0 ... n] to [1 ... n]
        currBlock = currCnd(1);% first number is the current block
        currCnd = currCnd(2:end);% third to n number are conditions
        currCndNum = length(currCnd);
        fprintf(1,'\nBLOCK ');fprintf(1,'%u ',currBlock);
        fprintf(1,'\nCONDITION ');fprintf(1,'%u ',currCnd);
        fprintf(logfid,'\nBLOCK ');fprintf(logfid,'%u ',currBlock);
        fprintf(logfid,'\nCONDITION ');fprintf(logfid,'%u ',currCnd);
    elseif eventdata(3)== p.SendParamStart%-------------------------------------------------------------------------------------------------
        paramcnt = 0;
        eventdata(1:3) = -1001;
        paramsendflag = 0;
        while ~paramsendflag
            eventdata = invoke(cheetah,'GetEventDataAsDouble',p.EventObjName);
            % read upcoming events as parameter values
            if (eventdata(1) < 0);
                pause(.01);
            elseif (eventdata(1) > 0 & eventdata(3) > 0)
                [paramTime,paramID,paramTTL,paramBINhi,paramBINlo,paramcnt] = registerevent(eventdata,paramTime,paramID,paramTTL,paramBINhi,paramBINlo,paramcnt);
                % detect end of stimparameter (pattern: p.SendParamEnd 0 p.SendParamEnd)
                if (paramcnt>=2) & (paramTTL(paramcnt-1)==p.SendParamEnd & paramTTL(paramcnt)==p.SendParamEnd)
                    paramsendflag = 1;
                    % print param events to logfile
                    for i = 1:paramcnt
                        printeventmessage(logfid,paramTime,paramID,paramTTL,paramBINhi,paramBINlo,[],i);
                    end
                    % take last p.SendParamEnd as end of sending
                    [evTime,evID,evTTL,evBINhi,evBINlo,evcnt] = registerevent(eventdata,evTime,evID,evTTL,evBINhi,evBINlo,evcnt);
                    printeventmessage(logfid,evTime,evID,evTTL,evBINhi,evBINlo,p,evcnt);
                    % neglect last 2 entries (stop event)
                    paramcnt = paramcnt-2;
                    fprintf(1,'\n==> ');fprintf(1,'(%u values): ',paramcnt);fprintf(1,'%u ',paramTTL(1:paramcnt));
                    fprintf(logfid,'\n==> ');fprintf(logfid,'(%u values): ',paramcnt);fprintf(logfid,'%u ',paramTTL(1:paramcnt));
                    break;
                end
            end
        end
        paramArray = [paramTime(1:paramcnt)' paramTTL(1:paramcnt)'];
        % first parameter should give numbers of parameter
        if paramcnt~=paramTTL(1)
            fprintf(1,'\nWARNING: unexpected number of parameter -> do_READ_flag = 0!');
            fprintf(logfid,'\nWARNING: unexpected number of parameter -> do_READ_flag = 0!');
            do_READ_flag = 0; % dont read data if there are any
            %irregularities in the number of parameters
        end
    elseif eventdata(3)== p.TrialEndEvent%-------------------------------------------------------------------------------------------------
        % add trial end event to @al_spk object
        if is_READ_flag
            for i=trialcnt4
                s.events{p.EventCode == p.TrialEndEvent,i} = evTime(evTTL==p.TrialEndEvent) - s.align(i);
            end
        end
        currCnd = NaN;
        trialcnt4 = zeros(1,p.PresentationNum).*NaN;
        evcnt = 0;
        fprintf(logfid,'\nEND OF TRIAL');
        fprintf(1,'\nEND OF TRIAL');
        % empty spike buffer from useless spike data
        flushwin = [0 eventdata(1)];
        [spikedata,flushnum] = flushspikes(cheetah,p.SpikeObjName{1},flushwin);
        fprintf(logfid,['\nSPIKES: %5u flushed \t%u %u'],flushnum,flushwin(1),flushwin(2));
        TRIAL_HANDBRAKE = 1;
    elseif eventdata(3)== p.ReadDataEvent%-------------------------------------------------------------------------------------------------
        % check for save reading of trial data
        if any(~ismember(p.MandatoryEvents,evTTL))
            fprintf(1,['\nWARNING: OMIT trial due to MISSING EVENTS ' num2str(p.MandatoryEvents(~ismember(p.MandatoryEvents,evTTL))) ' !']);
            fprintf(logfid,['\nWARNING: OMIT trial due to MISSING EVENTS ' num2str(p.MandatoryEvents(~ismember(p.MandatoryEvents,evTTL))) ' !']);
        elseif currCndNum ~=p.PresentationNum
            fprintf(1,['\nWARNING: OMIT trial due to NON EXPECTED NUMBER OF PRESENTATIONS !']);
            fprintf(logfid,['\nWARNING: OMIT trial due to NON EXPECTED NUMBER OF PRESENTATIONS !']);
        elseif ~do_READ_flag
            fprintf(1,['\nWARNING: OMIT trial due to do_READ_flag=0 !']);
            fprintf(logfid,['\nWARNING: OMIT trial due to do_READ_flag=0 !']);
        elseif any(~ismember(currCnd,[1:p.Cndnum]))
            fprintf(1,['\nWARNING: OMIT trial due to wrong condition information !']);
            fprintf(logfid,['\nWARNING: OMIT trial due to wrong condition information!']);
        else
            %
            is_READ_flag = 1;
            % empty spike buffer from useless spike data
            flushwin = [0 evTime(evTTL==p.AcqEvents(1))+p.AcqOffset(1)-1];
            if spikedata(1)<flushwin(2)
                [spikedata,flushnum] = flushspikes(cheetah,p.SpikeObjName{1},flushwin);
                fprintf(logfid,['\nSPIKES: %5u flushed \t%u %u'],flushnum,flushwin(1),flushwin(2));
            end
            % get valid spikes
            spkcnt = 0;
            while (spikedata(1) >= 0) & (spikedata(1) >= evTime(evTTL==p.AcqEvents(1))+p.AcqOffset(1).*0.001) & (spikedata(1) <= evTime(evTTL==p.AcqEvents(2))+p.AcqOffset(2).*0.001)
                spkcnt = spkcnt + 1;
                spkTime(spkcnt) = spikedata(1);
                spkChannel(spkcnt) = spikedata(2);
                spkCell(spkcnt) = spikedata(3);
                spikedata = invoke(cheetah,'GetSpikeDataAsDouble',p.SpikeObjName{1});
            end
            % message
            fprintf(1,'\nSPIKES: %5u read \t%u %u ',spkcnt,(evTime(evTTL==p.AcqEvents(1))+p.AcqOffset(1).*1000),(evTime(evTTL==p.AcqEvents(2))+p.AcqOffset(2).*1000));
            fprintf(logfid,'\nSPIKES: %5u read \t%u %u ',spkcnt,(evTime(evTTL==p.AcqEvents(1))+p.AcqOffset(1).*1000),(evTime(evTTL==p.AcqEvents(2))+p.AcqOffset(2).*1000));
            %++++++++++++++ read data into structure ++++++++++++++++++++++++++++++++++++
            % convert to ms
            evTime = evTime.*0.001;
            spkTime = spkTime.*0.001;
            %----------------------------------------------------------
            % specific windows for each single condition/presentation
            % get condition specific acquisition times
            LoWin = evTime(ismember(evTTL,p.CndAcqEventsLo)) + p.CndAcqOffset(1);
            HiWin = evTime(ismember(evTTL,p.CndAcqEventsHi)) + p.CndAcqOffset(2);
            AlignTime = evTime(ismember(evTTL,p.CndAlignEvent)) + p.CndAlignOffset;
            % make sure you get as many windows as pesented conditions
            LoWin = LoWin(1:p.PresentationNum);
            HiWin = HiWin(1:p.PresentationNum);
            AlignTime = AlignTime(1:p.PresentationNum);
            % set spike acquisition limits for conditions of first and last stimulus
            % presentation
            LoWin(1) = evTime(evTTL==p.AcqEvents(1))+p.AcqOffset(1).*0.001;
            HiWin(end) = evTime(evTTL==p.AcqEvents(2))+p.AcqOffset(2).*0.001;
            %----------------------------------------------------------
            % read data into @al_spk object
            for i = 1:p.PresentationNum
                trialcnt = trialcnt+1;
                trialcnt2 = trialcnt2 + 1;
                trialcnt4(i) = trialcnt2;
                s.trialcode(spk_BlockInd,trialcnt) = currBlock;
                s.trialcode(spk_CndInd,trialcnt) = currCnd(i);
                s.trialcode(spk_TrialInd,trialcnt) = trialcnt2;
                s.trialcode(spk_PresentNrInd,trialcnt) = i;
                s.trialcode(spk_trialcountInd) = trialcnt3;
                s.trialcode(spk_timeInd) = currTrialTime;
                s.align(trialcnt) = AlignTime(i);
                % every trial in data structure has ALL the vents of a
                % cortex trial
                for j=1:length(p.EventCode)
                    s.events{j,trialcnt} = evTime(evTTL==p.EventCode(j)) - s.align(trialcnt);
                end
                for k = 1:p.SpikeChanNum
                    % get the spikes within the current condition/presentation window
                    s.spk{k,trialcnt} = spkTime(spkCell==(k-1) & spkTime>=LoWin(i) & spkTime<=HiWin(i)) - s.align(trialcnt);
                    % get all the spikes within the data acquisition window
                    %                         s.spk{k,trialcnt} = spkTime(spkCell==(k-1)) - s.align(trialcnt);
                end
                s.stimulus{trialcnt} = paramArray;
            end
            % convert to microms
            evTime = evTime.*1000;
            spkTime = spkTime.*1000;
            %++++++++++++++ analyse data ++++++++++++++++++++++++++++++++++++
            for f = 1:size(dofun,1)
                feval(dofun{f,:},s,[trialcnt-(currCndNum-1):trialcnt],p);
            end
        end%read end
    else
    end% end switch
    eventdata(1) = -1001;
    if isempty(FH)
        assignin('base','SPK',s);
    else
        set(FH,'userdata',s);
    end
end
fprintf(logfid,'\n');
fprintf(logfid,['-------------------------------------------------------------------------------\n']);
fprintf(logfid,['log file closed: ' datestr(currtime,0) ' NLX time: %u\n'],invoke(cheetah,'GetTimeStampAsDouble'));
fprintf(logfid,['-------------------------------------------------------------------------------\n']);
fprintf(logfid,'\n');
fprintf(logfid,'\n');
fclose(logfid);
return
%==========================================================================
function [evTime,evID,evTTL,evBINhi,evBINlo,evcnt] = registerevent(eventdata,evTime,evID,evTTL,evBINhi,evBINlo,evcnt)
if eventdata(1)<0;return;end
% convert negative evTTL, interpreting negative integers as 2's
% complement
if eventdata(3)<0
    eventdata(3) = 2*2^(16-1) + eventdata(3);
end
if eventdata(3)==0
    % zero events are not registered !
elseif eventdata(3)>0
    evcnt = evcnt + 1;
    evTime(evcnt)   = eventdata(1);
    evID(evcnt)     = eventdata(2);
    evTTL(evcnt)    = eventdata(3);
    currBinary       = fliplr(dec2bin(eventdata(3),16));
    evBINhi(evcnt,1:8)       =  fliplr(currBinary(9:16));
    evBINlo(evcnt,1:8)       =  fliplr(currBinary(1:8));
end
%==========================================================================
function printeventmessage(logfid,evTime,evID,evTTL,evBINhi,evBINlo,p,evcnt)
    %______________________________________________________________________
    % print event message
    if ~isempty(p) & (p.PrintEventEcho==0)
        return;
    end
    fprintf(logfid,'\n');
    fprintf(logfid,'%5u ',evcnt);
    fprintf(logfid,'%12u ',evTime(evcnt));
    fprintf(logfid,'%4u ',evID(evcnt));
    fprintf(logfid,'%5u ',evTTL(evcnt));
    fprintf(logfid,[evBINhi(evcnt,:) ' ']);
    fprintf(logfid,[evBINlo(evcnt,:) ' ']);
    fprintf(logfid,'# ');
    lastEvent = find(evTime<evTime(evcnt) & evTTL~=0);
    if evcnt>1 & ~isempty(lastEvent)
        fprintf(logfid,'+%9f ms ',(evTime(evcnt)-evTime(lastEvent(end))).*0.001);
    else
        fprintf(logfid,' %9f ms ',evTime(evcnt).*0.001);
    end
    if ~isempty(p)
        fprintf(logfid,['    ' p.EventName{p.EventCode==evTTL(evcnt)}]);
    end
%==========================================================================
function [spikedata,flushnum] = flushspikes(cheetah,cheetahobjname,flushwin)
flushnum = 0;
pausenum = 0;
spikedata = -1001;
spikedata = invoke(cheetah,'GetSpikeDataAsDouble',cheetahobjname);
if spikedata(1)==-101
    error('no cheetah object available ...');
end
while (spikedata(1) == -1001) | (spikedata(1)>=flushwin(1) & spikedata(1)<=flushwin(2))
    if spikedata(1) == -1001
        pause(0.01);
        pausenum = pausenum +1;
        if pausenum>2;break;end
    else
        flushnum = flushnum +1;
    end
    spikedata = invoke(cheetah,'GetSpikeDataAsDouble',cheetahobjname);
end
%==========================================================================
function [eventdata,flushnum] = flushevents(cheetah,cheetahobjname,flushwin)
flushnum = 0;
pausenum = 0;
eventdata = -1001;
eventdata = invoke(cheetah,'GetEventDataAsDouble',cheetahobjname);
if eventdata(1)==-101
    error('no cheetah object available ...');
end
while (eventdata(1) == -1001) | (eventdata(1)>=flushwin(1) & eventdata(1)<=flushwin(2))
    if eventdata(1) == -1001
        pause(0.01);
        pausenum = pausenum +1;
        if pausenum>2;break;end
    else
        flushnum = flushnum +1;
    end
    eventdata = invoke(cheetah,'GetEventDataAsDouble',cheetahobjname);
end